#!/usr/bin/env bash
# Configures an Nginx server installation to listening on port 80.

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
